# NumPy

In [1]:
import numpy as np

### lets do some basic stuff

In [3]:
a = np.array(5)
a

array(5)

In [13]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
a = a.reshape(2, 5, 2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [15]:
print (a.shape)
print (a.ndim)
print (a.size)
print (a.dtype)

(2, 5, 2)
3
20
int32


In [23]:
a = np.ones((3, 4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### some operations

In [27]:
a = np.array([20, 30, 40, 50])
b = np.arange(4)

In [28]:
a, b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [29]:
a + b

array([20, 31, 42, 53])

In [32]:
c = a * b
c

array([  0,  30,  80, 150])

In [33]:
np.sin(c)

array([ 0.        , -0.98803162, -0.99388865, -0.71487643])

In [36]:
c > 50

array([False, False,  True,  True])